namespace RPG_Assistant.Enums;

public enum ExpertiseType {
    Acrobacia,
    Adestramento,
    Atletismo,
    Atuacao,
    Cavalgar,
    Conhecimento,
    Cura,
    Diplomacia,
    Enganacao,
    Fortitude,
    Furtividade,
    Guerra,
    Iniciativa,
    Intimidacao,
    Intuicao,
    Investigacao,
    Jogatina,
    Ladinagem,
    Luta,
    Misticismo,
    Nobreza,
    Oficio,
    Percepcao,
    Pilotagem,
    Pontaria,
    Reflexos,
    Religiao,
    Sobrevivencia,
    Vontade
}